### ISSUE TITLE
powercfg code page error

### ISSUE THREAD

**Issue by sergej3** [M-y/auto-brightness#1]
I'm getting the error message: Failed to execute script __main__ on 1.6.1 and 1.5.1
I'm on Windows 10 Pro x64 if it helps

**Comment by M-y** [comment]
On first time you run the exe?

**Comment by sergej3** [comment]
the Error Message Always appears when i'm trying to run the exe

**Comment by M-y** [comment]
I have added a new download asset named **autobrightness_1.6.1-windows_debug.zip**. You can find it in [1.6.1 release page](https://github.com/M-y/auto-brightness/releases/tag/1.6.1). Could you try it then share the result here.

**Comment by sergej3** [comment]
here's the link to an image with the output https://ibb.co/RgnPrwd
also thank you for your help!

**Comment by M-y** [comment]
Np, always feel free to open an issue to report bugs or request a feature.

Now could you open cmd from your start menu and type `chcp` and press enter?

**Comment by sergej3** [comment]
the Output is: Aktive Codepage: 850.

Muhammed YILDIRIM <notifications@github.com> schrieb am Mi., 23. Sept.
2020, 09:40:

**Comment by M-y** [comment]
Can you copy and paste output here or take a screenshot?

23 Eyl 2020 Çar 10:53 tarihinde user22555 <notifications@github.com> şunu
yazdı:

**Comment by sergej3** [comment]
thats all its showing, there is unfortunately not more text

Muhammed YILDIRIM <notifications@github.com> schrieb am Mi., 23. Sept.
2020, 09:59:

**Comment by M-y** [comment]
I have asked because I need output without typo. Is it Aktive Codepage or
Active code page?

23 Eyl 2020 Çar 11:00 tarihinde user22555 <notifications@github.com> şunu
yazdı:

**Comment by sergej3** [comment]
it's "aktive" because my Windows is German language, the translation would
be "active" sorry for the misunderstanding

Muhammed YILDIRIM <notifications@github.com> schrieb am Mi., 23. Sept.
2020, 10:07:

**Comment by M-y** [comment]
Ok. It will be fixed in ~12 hours.

23 Eyl 2020 Çar 11:12 tarihinde user22555 <notifications@github.com> şunu
yazdı:

**Comment by sergej3** [comment]
thank you very much sir 👍

Muhammed YILDIRIM <notifications@github.com> schrieb am Mi., 23. Sept.
2020, 10:14:
